collections:
  services:
    output: true
  ressources:
    output: true
exclude:
    - "*.iml"
    - README.md
    - Dockerfile
    - lib-catalogue/.vscode/
    - lib-catalogue/node_modules/
    - lib-catalogue/src/
    - lib-catalogue/public/
    - lib-catalogue/index.html
    - lib-catalogue/*.json
    - lib-catalogue/README.md
    - lib-catalogue/svelte.config.js
    - lib-catalogue/vite.config.ts
