services:
  bundle:
    container_name: mes-services-cyber-bundle
    build:
      context: .
      dockerfile: Dockerfile-bundle
    volumes:
      - ./front:/srv/bundle/front
      - /srv/bundle/node_modules
      - /srv/bundle/front/node_modules
      - /srv/bundle/front/lib-svelte/node_modules

  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5435:5432'
    volumes:
      - dbvol:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

volumes:
  dbvol:
    driver: local
