# _c.f._ https://pnpm.io/settings

color: always
packages:
  - 'back'
  - 'front'
  - 'front/lib-svelte'
  - 'recuperation-guides'
  - 'mise-a-jour-financements'
  - 'demande-diag'
  - 'comparaison-grist'

minimumReleaseAge: 10080 # 7 jours (exprimé en minutes)
preferFrozenLockfile: true

minimumReleaseAgeExclude:
  - svelte@5.53.5
  - minimatch@3.1.4 || 9.0.7 || 10.2.3