color: always
packages:
  - '*'
  - front/lib-svelte
  - webc-externes/*

minimumReleaseAge: 10080 # 7 jours (exprimé en minutes)
preferFrozenLockfile: true
strictDepBuilds: false

overrides:
  'shell-quote@>=1.1.0 <=1.8.3': '>=1.8.4'
  'svelte@<=5.55.6': '>=5.55.9'
  'vite@<=6.4.2': '8.3.0'
  'vitest@<4.1.0': '>=4.1.0'

allowBuilds:
  '@lab-anssi/lib': false
  '@lab-anssi/ui-kit': false
  '@parcel/watcher': false
  '@sentry/cli': false
  bcrypt: false
  esbuild: false

catalog:
  axios: ^1.18.0
  entities: ^8.0.0
  isomorphic-dompurify: ^4.0.0
  prettier: 3.9.9
  svelte: 5.57.1
  tsx: ^4.23.12
  uuid: ^14.0.1
  vitest: ^5.0.0

minimumReleaseAgeExclude:
  - '@lab-anssi/ui-kit'
  - '@lab-anssi/lib'
