# _c.f._ https://pnpm.io/settings

color: always
packages:
  - 'back'
  - 'front'
  - 'front/lib-svelte'
  - 'mise-a-jour-financements'
  - 'demande-diag'
  - 'comparaison-grist'

minimumReleaseAge: 10080 # 7 jours (exprimé en minutes)
preferFrozenLockfile: true

minimumReleaseAgeExclude:
  - devalue@5.6.4
  - undici@7.24.0
  - flatted@3.4.2
  - picomatch@4.0.4
  - path-to-regexp@0.1.13
  - brace-expansion@5.0.5 || 1.1.13
  - vite@6.4.2
  - lodash@4.18.1
  - axios@1.15.0
  - '@sentry/browser@10.48.0'
  - '@sentry-internal/*'
  - '@sentry/core@10.48.0'
