# _c.f._ https://pnpm.io/settings

color: always
packages:
  - 'back'
  - 'front'
  - 'front/lib-svelte'
  - 'recuperation-guides'

minimumReleaseAge: 10080 # 7 jours (exprimé en minutes)
preferFrozenLockfile: true
