import { CodeRegion } from './referentielRegions';

export const departements = [
  { nom: 'Ain', code: '01', codeRegion: 'FR-ARA' },
  { nom: 'Aisne', code: '02', codeRegion: 'FR-HDF' },
  { nom: 'Allier', code: '03', codeRegion: 'FR-ARA' },
  { nom: 'Alpes-de-Haute-Provence', code: '04', codeRegion: 'FR-PAC' },
  { nom: 'Hautes-Alpes', code: '05', codeRegion: 'FR-PAC' },
  { nom: 'Alpes-Maritimes', code: '06', codeRegion: 'FR-PAC' },
  { nom: 'Ardèche', code: '07', codeRegion: 'FR-ARA' },
  { nom: 'Ardennes', code: '08', codeRegion: 'FR-GES' },
  { nom: 'Ariège', code: '09', codeRegion: 'FR-OCC' },
  { nom: 'Aube', code: '10', codeRegion: 'FR-GES' },
  { nom: 'Aude', code: '11', codeRegion: 'FR-OCC' },
  { nom: 'Aveyron', code: '12', codeRegion: 'FR-OCC' },
  { nom: 'Bouches-du-Rhône', code: '13', codeRegion: 'FR-PAC' },
  { nom: 'Calvados', code: '14', codeRegion: 'FR-NOR' },
  { nom: 'Cantal', code: '15', codeRegion: 'FR-ARA' },
  { nom: 'Charente', code: '16', codeRegion: 'FR-NAQ' },
  { nom: 'Charente-Maritime', code: '17', codeRegion: 'FR-NAQ' },
  { nom: 'Cher', code: '18', codeRegion: 'FR-CVL' },
  { nom: 'Corrèze', code: '19', codeRegion: 'FR-NAQ' },
  { nom: "Côte-d'Or", code: '21', codeRegion: 'FR-BFC' },
  { nom: "Côtes-d'Armor", code: '22', codeRegion: 'FR-BRE' },
  { nom: 'Creuse', code: '23', codeRegion: 'FR-NAQ' },
  { nom: 'Dordogne', code: '24', codeRegion: 'FR-NAQ' },
  { nom: 'Doubs', code: '25', codeRegion: 'FR-BFC' },
  { nom: 'Drôme', code: '26', codeRegion: 'FR-ARA' },
  { nom: 'Eure', code: '27', codeRegion: 'FR-NOR' },
  { nom: 'Eure-et-Loir', code: '28', codeRegion: 'FR-CVL' },
  { nom: 'Finistère', code: '29', codeRegion: 'FR-BRE' },
  { nom: 'Corse-du-Sud', code: '2A', codeRegion: 'FR-20R' },
  { nom: 'Haute-Corse', code: '2B', codeRegion: 'FR-20R' },
  { nom: 'Gard', code: '30', codeRegion: 'FR-OCC' },
  { nom: 'Haute-Garonne', code: '31', codeRegion: 'FR-OCC' },
  { nom: 'Gers', code: '32', codeRegion: 'FR-OCC' },
  { nom: 'Gironde', code: '33', codeRegion: 'FR-NAQ' },
  { nom: 'Hérault', code: '34', codeRegion: 'FR-OCC' },
  { nom: 'Ille-et-Vilaine', code: '35', codeRegion: 'FR-BRE' },
  { nom: 'Indre', code: '36', codeRegion: 'FR-CVL' },
  { nom: 'Indre-et-Loire', code: '37', codeRegion: 'FR-CVL' },
  { nom: 'Isère', code: '38', codeRegion: 'FR-ARA' },
  { nom: 'Jura', code: '39', codeRegion: 'FR-BFC' },
  { nom: 'Landes', code: '40', codeRegion: 'FR-NAQ' },
  { nom: 'Loir-et-Cher', code: '41', codeRegion: 'FR-CVL' },
  { nom: 'Loire', code: '42', codeRegion: 'FR-ARA' },
  { nom: 'Haute-Loire', code: '43', codeRegion: 'FR-ARA' },
  { nom: 'Loire-Atlantique', code: '44', codeRegion: 'FR-PDL' },
  { nom: 'Loiret', code: '45', codeRegion: 'FR-CVL' },
  { nom: 'Lot', code: '46', codeRegion: 'FR-OCC' },
  { nom: 'Lot-et-Garonne', code: '47', codeRegion: 'FR-NAQ' },
  { nom: 'Lozère', code: '48', codeRegion: 'FR-OCC' },
  { nom: 'Maine-et-Loire', code: '49', codeRegion: 'FR-PDL' },
  { nom: 'Manche', code: '50', codeRegion: 'FR-NOR' },
  { nom: 'Marne', code: '51', codeRegion: 'FR-GES' },
  { nom: 'Haute-Marne', code: '52', codeRegion: 'FR-GES' },
  { nom: 'Mayenne', code: '53', codeRegion: 'FR-PDL' },
  { nom: 'Meurthe-et-Moselle', code: '54', codeRegion: 'FR-GES' },
  { nom: 'Meuse', code: '55', codeRegion: 'FR-GES' },
  { nom: 'Morbihan', code: '56', codeRegion: 'FR-BRE' },
  { nom: 'Moselle', code: '57', codeRegion: 'FR-GES' },
  { nom: 'Nièvre', code: '58', codeRegion: 'FR-BFC' },
  { nom: 'Nord', code: '59', codeRegion: 'FR-HDF' },
  { nom: 'Oise', code: '60', codeRegion: 'FR-HDF' },
  { nom: 'Orne', code: '61', codeRegion: 'FR-NOR' },
  { nom: 'Pas-de-Calais', code: '62', codeRegion: 'FR-HDF' },
  { nom: 'Puy-de-Dôme', code: '63', codeRegion: 'FR-ARA' },
  { nom: 'Pyrénées-Atlantiques', code: '64', codeRegion: 'FR-NAQ' },
  { nom: 'Hautes-Pyrénées', code: '65', codeRegion: 'FR-OCC' },
  { nom: 'Pyrénées-Orientales', code: '66', codeRegion: 'FR-OCC' },
  { nom: 'Bas-Rhin', code: '67', codeRegion: 'FR-GES' },
  { nom: 'Haut-Rhin', code: '68', codeRegion: 'FR-GES' },
  { nom: 'Rhône', code: '69', codeRegion: 'FR-ARA' },
  { nom: 'Haute-Saône', code: '70', codeRegion: 'FR-BFC' },
  { nom: 'Saône-et-Loire', code: '71', codeRegion: 'FR-BFC' },
  { nom: 'Sarthe', code: '72', codeRegion: 'FR-PDL' },
  { nom: 'Savoie', code: '73', codeRegion: 'FR-ARA' },
  { nom: 'Haute-Savoie', code: '74', codeRegion: 'FR-ARA' },
  { nom: 'Paris', code: '75', codeRegion: 'FR-IDF' },
  { nom: 'Seine-Maritime', code: '76', codeRegion: 'FR-NOR' },
  { nom: 'Seine-et-Marne', code: '77', codeRegion: 'FR-IDF' },
  { nom: 'Yvelines', code: '78', codeRegion: 'FR-IDF' },
  { nom: 'Deux-Sèvres', code: '79', codeRegion: 'FR-NAQ' },
  { nom: 'Somme', code: '80', codeRegion: 'FR-HDF' },
  { nom: 'Tarn', code: '81', codeRegion: 'FR-OCC' },
  { nom: 'Tarn-et-Garonne', code: '82', codeRegion: 'FR-OCC' },
  { nom: 'Var', code: '83', codeRegion: 'FR-PAC' },
  { nom: 'Vaucluse', code: '84', codeRegion: 'FR-PAC' },
  { nom: 'Vendée', code: '85', codeRegion: 'FR-PDL' },
  { nom: 'Vienne', code: '86', codeRegion: 'FR-NAQ' },
  { nom: 'Haute-Vienne', code: '87', codeRegion: 'FR-NAQ' },
  { nom: 'Vosges', code: '88', codeRegion: 'FR-GES' },
  { nom: 'Yonne', code: '89', codeRegion: 'FR-BFC' },
  { nom: 'Territoire de Belfort', code: '90', codeRegion: 'FR-BFC' },
  { nom: 'Essonne', code: '91', codeRegion: 'FR-IDF' },
  { nom: 'Hauts-de-Seine', code: '92', codeRegion: 'FR-IDF' },
  { nom: 'Seine-Saint-Denis', code: '93', codeRegion: 'FR-IDF' },
  { nom: 'Val-de-Marne', code: '94', codeRegion: 'FR-IDF' },
  { nom: "Val-d'Oise", code: '95', codeRegion: 'FR-IDF' },
  { nom: 'Guadeloupe', code: '971', codeRegion: 'FR-971' },
  { nom: 'Martinique', code: '972', codeRegion: 'FR-972' },
  { nom: 'Guyane', code: '973', codeRegion: 'FR-973' },
  { nom: 'La Réunion', code: '974', codeRegion: 'FR-974' },
  { nom: 'Saint-Pierre-et-Miquelon', code: '975', codeRegion: 'FR-PM' },
  { nom: 'Mayotte', code: '976', codeRegion: 'FR-976' },
  { nom: 'Saint-Barthélemy', code: '977', codeRegion: 'FR-BL' },
  { nom: 'Saint-Martin', code: '978', codeRegion: 'FR-MF' },
  {
    nom: 'Terres australes et antarctiques françaises',
    code: '984',
    codeRegion: 'FR-TF',
  },
  { nom: 'Wallis et Futuna', code: '986', codeRegion: 'FR-WF' },
  { nom: 'Polynésie française', code: '987', codeRegion: 'FR-PF' },
  { nom: 'Nouvelle-Calédonie', code: '988', codeRegion: 'FR-NC' },
  { nom: 'Île de Clipperton', code: '989', codeRegion: 'FR-CP' },
] as const;

export const codeDepartement = departements.map((s) => s.code);

export const estCodeDepartement = (
  code: string | undefined | null
): code is CodeDepartement => departements.some((d) => d.code === code);

export const regionDuDepartement = (
  codeDepartement: CodeDepartement | undefined
): CodeRegion | undefined =>
  departements.find((d) => d.code === codeDepartement)?.codeRegion;

export type CodeDepartement = (typeof codeDepartement)[number];
