import { CmsCrisp } from '@lab-anssi/lib';
import { BusEvenements } from '../bus/busEvenements.js';
import { AdaptateurCellar } from '../infra/adaptateurCellar.js';
import { AdaptateurEnvironnement } from '../infra/adaptateurEnvironnement.js';
import { AdaptateurGestionErreur } from '../infra/adaptateurGestionErreurSentry.js';
import { AdaptateurHachage } from '../infra/adaptateurHachage.js';
import { AdaptateurMonAideCyber } from '../infra/adaptateurMonAideCyber.js';
import { AdaptateurProfilAnssi } from '../infra/adaptateurProfilAnssi.js';
import { AdaptateurRechercheEntreprise } from '../infra/adaptateurRechercheEntreprise.js';
import { GenerateurImage } from '../infra/generateurImage.js';
import { AdaptateurEmail } from '../metier/adaptateurEmail.js';
import { EntrepotFavori } from '../metier/entrepotFavori.js';
import { EntrepotFinancement } from '../metier/entrepotFinancement.js';
import { EntrepotGuide } from '../metier/entrepotGuide.js';
import { EntrepotGuideTravail } from '../metier/entrepotGuideTravail.js';
import { EntrepotMesure } from '../metier/entrepotMesure.js';
import { EntrepôtModule } from '../metier/EntrepotModule.js';
import { EntrepotPriseEnCompte } from '../metier/entrepotPriseEnCompte.js';
import { EntrepotResultatTest } from '../metier/entrepotResultatTest.js';
import { EntrepotSessionDeGroupe } from '../metier/entrepotSessionDeGroupe.js';
import { EntrepotUtilisateur } from '../metier/entrepotUtilisateur.js';
import { GenerateurCodeSessionDeGroupe } from '../metier/generateurCodeSessionDeGroupe.js';
import { MessagerieInstantanee } from '../metier/messagerieInstantanee.js';
import { EntrepotExigence } from '../metier/nis2/entrepotExigence.js';
import { ServiceSanteGuides } from '../metier/serviceSanteGuides.js';
import { AdaptateurJWT } from './adaptateurJWT.js';
import { FournisseurChemin } from './fournisseurChemin.js';
import { Middleware } from './middleware.js';
import { AdaptateurOIDC } from './oidc/adaptateurOIDC.js';

export type ConfigurationServeur = {
  adaptateurEnvironnement: AdaptateurEnvironnement;
  adaptateurGestionErreur: AdaptateurGestionErreur;
  adaptateurHachage: AdaptateurHachage;
  adaptateurJWT: AdaptateurJWT;
  adaptateurMonAideCyber: AdaptateurMonAideCyber;
  adaptateurOIDC: AdaptateurOIDC;
  adaptateurProfilAnssi: AdaptateurProfilAnssi;
  adaptateurRechercheEntreprise: AdaptateurRechercheEntreprise;
  busEvenements: BusEvenements;
  cmsCrisp: CmsCrisp;
  entrepotFavori: EntrepotFavori;
  entrepotFinancement: EntrepotFinancement;
  entrepotGuide: EntrepotGuide;
  entrepotGuideTravail: EntrepotGuideTravail;
  entrepotResultatTest: EntrepotResultatTest;
  entrepotSessionDeGroupe: EntrepotSessionDeGroupe;
  entrepotUtilisateur: EntrepotUtilisateur;
  entrepotExigence: EntrepotExigence;
  entrepotMesure: EntrepotMesure;
  entrepotPriseEnCompte: EntrepotPriseEnCompte;
  entrepôtModule: EntrepôtModule;
  fournisseurChemin: FournisseurChemin;
  generateurCodeSessionDeGroupe: GenerateurCodeSessionDeGroupe;
  messagerieInstantanee: MessagerieInstantanee;
  middleware: Middleware;
  reseau: {
    trustProxy: number | string;
    maxRequetesParMinutes: number;
    maxRequetesParMinuteAPI: number;
    ipAutorisees: string[] | false;
  };
  cellar: AdaptateurCellar;
  serviceSanteGuides: ServiceSanteGuides;
  adaptateurEmail: AdaptateurEmail;
  generateurImage: GenerateurImage;
};
