import { CmsCrisp } from '@lab-anssi/lib';
import { BusEvenements } from '../bus/busEvenements';
import { AdaptateurCellar } from '../infra/adaptateurCellar';
import { AdaptateurEnvironnement } from '../infra/adaptateurEnvironnement';
import { AdaptateurGestionErreur } from '../infra/adaptateurGestionErreurSentry';
import { AdaptateurHachage } from '../infra/adaptateurHachage';
import { AdaptateurMonAideCyber } from '../infra/adaptateurMonAideCyber';
import { AdaptateurProfilAnssi } from '../infra/adaptateurProfilAnssi';
import { AdaptateurRechercheEntreprise } from '../infra/adaptateurRechercheEntreprise';
import { EntrepotExigence } from '../metier/EntrepotExigence';
import { EntrepotFavori } from '../metier/entrepotFavori';
import { EntrepotFinancement } from '../metier/entrepotFinancement';
import { EntrepotGuide } from '../metier/entrepotGuide';
import { EntrepotResultatTest } from '../metier/entrepotResultatTest';
import { EntrepotSessionDeGroupe } from '../metier/entrepotSessionDeGroupe';
import { EntrepotUtilisateur } from '../metier/entrepotUtilisateur';
import { GenerateurCodeSessionDeGroupe } from '../metier/generateurCodeSessionDeGroupe';
import { MessagerieInstantanee } from '../metier/messagerieInstantanee';
import { AdaptateurJWT } from './adaptateurJWT';
import { FournisseurChemin } from './fournisseurChemin';
import { Middleware } from './middleware';
import { AdaptateurOIDC } from './oidc/adaptateurOIDC';

export type ConfigurationServeur = {
  adaptateurEnvironnement: AdaptateurEnvironnement;
  adaptateurGestionErreur: AdaptateurGestionErreur;
  adaptateurHachage: AdaptateurHachage;
  adaptateurJWT: AdaptateurJWT;
  adaptateurMonAideCyber: AdaptateurMonAideCyber;
  adaptateurOIDC: AdaptateurOIDC;
  adaptateurProfilAnssi: AdaptateurProfilAnssi;
  adaptateurRechercheEntreprise: AdaptateurRechercheEntreprise;
  busEvenements: BusEvenements;
  cmsCrisp: CmsCrisp;
  entrepotFavori: EntrepotFavori;
  entrepotFinancement: EntrepotFinancement;
  entrepotGuide: EntrepotGuide;
  entrepotResultatTest: EntrepotResultatTest;
  entrepotSessionDeGroupe: EntrepotSessionDeGroupe;
  entrepotUtilisateur: EntrepotUtilisateur;
  entrepotExigence: EntrepotExigence;
  fournisseurChemin: FournisseurChemin;
  generateurCodeSessionDeGroupe: GenerateurCodeSessionDeGroupe;
  messagerieInstantanee: MessagerieInstantanee;
  middleware: Middleware;
  reseau: {
    trustProxy: number | string;
    maxRequetesParMinutes: number;
    ipAutorisees: string[] | false;
  };
  cellar: AdaptateurCellar;
};
