// Fichier généré automatiquement au build Svelte (emetComposantsAutorisés). Ne pas modifier à la main.
export const composantsAutorisés: string[] = [
  'entreprises',
  'associations',
  'navigation',
  'collectivites',
  'catalogue',
  'page-directive-nis2',
  'guide',
  'financements',
  'page-crisp',
  'fil-ariane',
  'test-maturite',
  'session-groupe',
  'demande-diagnostic',
  'carrousel-des-interlocuteurs',
  'equipe-biz-dev',
  'demande-aide-mon-aide-cyber',
  'heros-accueil',
  'proteger-organisation',
  'parcours-securisation',
  'parcours-cyberdepart',
  'parcours-securisation-complet',
  'illustration-connexion-inscription',
  'mini-tests',
  'mini-test-vrai-faux',
  'mini-test-vrai-faux-quiz',
];
