name: Compare les financements
run-name: Génère le rapport de comparaison des financements
permissions: {}

on:
  workflow_dispatch: # Pour activer le déclenchement manuel
  schedule:
    - cron: '0 6 * * 1' # Tous les lundis à 06:00

jobs:
  genere-rapport:
    name: 'Génère rapport'
    runs-on: ubuntu-latest
    environment: FINANCEMENTS
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configurer Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Installe pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10.34.5

      - name: (TOUS) Installe les dépendances
        run: pnpm install --frozen-lockfile

      - name: Lance le script de comparaison
        env:
          FINANCEMENTS_GRIST_URL: ${{ secrets.FINANCEMENTS_GRIST_URL }}
          FINANCEMENTS_GRIST_API_KEY: ${{ secrets.FINANCEMENTS_GRIST_API_KEY }}
          AIDES_ENTREPRISES_URL: ${{ secrets.AIDES_ENTREPRISES_URL }}
          AIDES_ENTREPRISES_API_URL: ${{ secrets.AIDES_ENTREPRISES_API_URL }}
          AIDES_ENTREPRISES_API_ID: ${{ secrets.AIDES_ENTREPRISES_API_ID }}
          AIDES_ENTREPRISES_API_KEY: ${{ secrets.AIDES_ENTREPRISES_API_KEY }}
        run: pnpm -F mise-a-jour-financements start

      - name: Publie le rapport
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: rapport-financements
        with:
          name: rapport
          path: ./mise-a-jour-financements/rapports/financements-en-differences.html

      - name: Poste l'url du rapport
        uses: mattermost/action-mattermost-notify@ae31bb6f9e26a54336e79696f108a2c91cf55b4e # v2.1.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_FINANCEMENT_WEBHOOK_URL }}
          TEXT: |
            Nouveau rapport publié [ici](${{ steps.rapport-financements.outputs.artifact-url }})
