name: Déploiement Node
permissions: {}

on:
  workflow_call:
    inputs:
      nom:
        required: true
        type: string
      environnement:
        required: true
        type: string
    secrets:
      CLEVER_CLOUD_SECRET:
        required: true
      CLEVER_CLOUD_TOKEN:
        required: true
      CLEVER_CLOUD_ID_APP:
        required: true

jobs:
  deploiement-node:
    runs-on: ubuntu-latest
    name: ${{ inputs.nom }}
    environment: ${{ inputs.environnement }}
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Cloner l'intégralité du dépôt, pour ne pas avoir de « shallow repo » rejeté par Clever
          persist-credentials: false

      - name: Configurer Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Installe pnpm
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          install: false

      - name: (TOUS) Installe les dépendances
        run: pnpm install --frozen-lockfile

      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '4.0.5'
          bundler-cache: true
          cache-version: 0
          working-directory: ./front

      - name: Installer la CLI Clever Cloud
        shell: bash
        run: npm install -g clever-tools@4.4.0

      - name: Connecter à Clever
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_CLOUD_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_CLOUD_TOKEN }}
          ID_APP: ${{ secrets.CLEVER_CLOUD_ID_APP }}
        run: |
          clever link "$ID_APP"

          clever env |
            grep -E \
              -e '^SENTRY_AUTH_TOKEN=' \
              -e '^SENTRY_PROJET=' \
              -e '^SENTRY_URL=' \
              -e '^DELAI_AFFICHAGE_AVIS_UTILISATEUR=' \
              -e '^FEATURE_FLAG_NIS2_CYFUN23=' \
              -e '^FEATURE_FLAG_PARCOURS_SECURISATION=' \
              -e '^GOOGLE_SEARCH_CONSOLE_VERIFICATION=' \
              -e '^MATOMO_ID=' \
              -e '^MATOMO_URL_TAG_MANAGER=' \
              -e '^SENTRY_DSN=' \
              -e '^URL_BASE_MSC=' \
              -e '^SENTRY_ENVIRONNEMENT=' |
            tr -d '"' | while IFS='=' read -r key value; do
              echo "::add-mask::$value"
              echo "$key=$value" >> "$GITHUB_ENV"
            done

      - name: Construis la lib Svelte
        run: |
          pnpm --filter @anssi-portail/svelte build

      - name: Construis avec Jekyll
        run: |
          bundle config set --local path './front/vendor/bundle'
          bundle exec --gemfile=./front/Gemfile jekyll build -s ./front -d ./front/_site
        env:
          JEKYLL_ENV: production

      - name: Déployer sur Clever Cloud
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_CLOUD_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_CLOUD_TOKEN }}
          ID_APP: ${{ secrets.CLEVER_CLOUD_ID_APP }}
        run: |
          git config --global user.email "contact@messervicescyber.beta.gouv.fr"
          git config --global user.name "MesServicesCyber"
          git add --force front/_site
          git commit -m "Ajoute le site généré"
          NODE_VERSION="$(./scripts/get-node-version.sh)"
          clever env set CC_NODE_VERSION "$NODE_VERSION"
          clever deploy --force --same-commit-policy=rebuild
