name: Déploiement WebComponents
permissions: {}

on:
  workflow_dispatch: # Pour activer le déclenchement manuel

jobs:
  mini-test-vrai-faux:
    uses: $/.github/workflows/deploiement-webc-unique.yml
    with:
      package: mini-test-vrai-faux
      repertoire: webc-externes/mini-test-vrai-faux
      environnement: WEB_COMPONENTS
      nom: WebComponent Vrai/Faux
    secrets:
      CLEVER_S3_ACCESS_KEY: ${{ secrets.CLEVER_S3_ACCESS_KEY }}
      CLEVER_S3_SECRET_KEY: ${{ secrets.CLEVER_S3_SECRET_KEY }}

  mini-test-exposition:
    uses: $/.github/workflows/deploiement-webc-unique.yml
    with:
      package: mini-test-exposition
      repertoire: webc-externes/mini-test-exposition
      environnement: WEB_COMPONENTS
      nom: WebComponent Exposition
    secrets:
      CLEVER_S3_ACCESS_KEY: ${{ secrets.CLEVER_S3_ACCESS_KEY }}
      CLEVER_S3_SECRET_KEY: ${{ secrets.CLEVER_S3_SECRET_KEY }}

  demande-diag:
    uses: $/.github/workflows/deploiement-webc-unique.yml
    with:
      package: demande-diag
      repertoire: demande-diag
      environnement: WEB_COMPONENTS
      nom: WebComponent Demande de diag
    secrets:
      CLEVER_S3_ACCESS_KEY: ${{ secrets.CLEVER_S3_ACCESS_KEY }}
      CLEVER_S3_SECRET_KEY: ${{ secrets.CLEVER_S3_SECRET_KEY }}
