name: Déploie les guides
run-name: Compare et déploie les guides de démo en prod
permissions: {}

on:
  workflow_dispatch: # Pour activer le déclenchement manuel

jobs:
  compare-et-deploie-guides:
    name: 'Guides'
    uses: ./.github/workflows/grist-deploiement.yml
    with:
      cible: guides
    secrets: inherit
  compare-et-deploie-cellar:
    name: 'Documents'
    uses: ./.github/workflows/cellar-deploiement.yml
    with:
      bucket-source: ${{ env.GUIDES_BUCKET_SOURCE }}
      bucket-cible: ${{ env.GUIDES_BUCKET_CIBLE }}
    secrets: inherit
