name: Déploie des Grist
run-name: Compare et déploie des documents Grist
permissions: {}

on:
  workflow_call:
    inputs:
      cible:
        description: 'Cible'
        type: string
        required: true
      environnement:
        description: Environnement GitHub
        type: string
        required: true
    secrets:
      SOURCE_GRIST_URL:
        required: true
      SOURCE_GRIST_ID_TABLE:
        required: true
      SOURCE_GRIST_API_KEY:
        required: true
      CIBLE_GRIST_URL:
        required: true
      CIBLE_GRIST_ID_TABLE:
        required: true
      CIBLE_GRIST_API_KEY:
        required: true

jobs:
  genere-tableau-comparatif:
    name: Comparaison
    runs-on: ubuntu-latest
    environment: ${{ inputs.environnement }}
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configurer Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Installe pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 10.34.5

      - name: (TOUS) Installe les dépendances
        run: pnpm install --frozen-lockfile

      - name: Lance le script de comparaison
        run: pnpm -F comparaison-grist "start:${INPUTS_CIBLE}:compare"
        env:
          SOURCE_GRIST_URL: ${{ secrets.SOURCE_GRIST_URL }}
          SOURCE_GRIST_ID_TABLE: ${{ secrets.SOURCE_GRIST_ID_TABLE }}
          SOURCE_GRIST_API_KEY: ${{ secrets.SOURCE_GRIST_API_KEY }}
          CIBLE_GRIST_URL: ${{ secrets.CIBLE_GRIST_URL }}
          CIBLE_GRIST_ID_TABLE: ${{ secrets.CIBLE_GRIST_ID_TABLE }}
          CIBLE_GRIST_API_KEY: ${{ secrets.CIBLE_GRIST_API_KEY }}
          INPUTS_CIBLE: ${{ inputs.cible }}

      - name: Sauvegarde l'empreinte source
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: empreinte-data-${{ inputs.cible }}
          path: comparaison-grist/empreinte.txt

  deploie-ressources-grist:
    name: Déploiement
    runs-on: ubuntu-latest
    needs: genere-tableau-comparatif
    environment: DEPLOIEMENT_GUIDES
    steps:
      - name: Télécharger les empreintes sources
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: empreinte-data-${{ inputs.cible }}

      - name: Affiche les empreintes sources
        run: echo EMPREINTE=$(cat empreinte.txt) >> "$GITHUB_ENV"

      - name: Recopie le contenu
        id: copie
        run: |
          curl --request POST \
            --url ${{ secrets.CIBLE_GRIST_URL }}/replace \
            --header 'authorization: Bearer ${{ secrets.CIBLE_GRIST_API_KEY }}' \
            --header 'content-type: application/json' \
            --data "{
              \"sourceDocId\": \"${EMPREINTE}\"
            }" \
            || RC=$?
          echo "résultat : ${RC}"
          echo "rc=${RC:-0}" >> $GITHUB_OUTPUT

      - name: Échoue cas d'erreur
        if: steps.copie.outputs.rc != '0'
        run: |
          echo "❌ Erreur technique copie"
          exit 1
