name: L'intégration continue
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Construction du site
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configurer Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Installe pnpm
        uses: pnpm/setup@c8e77b72cd6022852162c92aa10e7e72b7209c9b # v2.0.2
        with:
          install: false

      - name: (TOUS) Installe les dépendances
        run: pnpm install --frozen-lockfile

      - name: Vérifie le formatage
        run: pnpm format:check

      - name: Exécute les tests
        run: pnpm test

      - name: Construis le back
        run: pnpm --filter @anssi-portail/back build

      - name: Construis la lib Svelte
        run: pnpm --filter @anssi-portail/svelte build

      - name: Setup Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '4.0.5'
          bundler-cache: true
          cache-version: 0
          working-directory: ./front

      - name: Construis avec Jekyll
        run: |
          bundle config set --local path './front/vendor/bundle'
          bundle exec --gemfile=./front/Gemfile jekyll build -s ./front -d ./front/_site
        env:
          JEKYLL_ENV: production
