name: L'intégration continue
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Construction du site
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Configurer Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'

      - name: Installe pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 10.34.5

      - name: (TOUS) Installe les dépendances
        run: pnpm install --frozen-lockfile

      - name: Exécute les tests
        run: pnpm test

      - name: Construis le back
        run: pnpm --filter @anssi-portail/back build

      - name: Construis la lib Svelte
        run: pnpm --filter @anssi-portail/svelte build

      - name: Setup Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: '4.0.5'
          bundler-cache: true
          cache-version: 0
          working-directory: ./front

      - name: Construis avec Jekyll
        run: |
          bundle config set --local path './front/vendor/bundle'
          bundle exec --gemfile=./front/Gemfile jekyll build -s ./front -d ./front/_site
        env:
          JEKYLL_ENV: production
